<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260209000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove category column from blog table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->addSql('ALTER TABLE blog DROP COLUMN category');
    }

    public function down(Schema $schema): void
    {
        // revert the up() operation
        $this->addSql('ALTER TABLE blog ADD category VARCHAR(255) DEFAULT NULL');
    }
}

